#include "RuleCoverageRegistry.hpp"

namespace azteca::plan
{

std::vector<RuleCoverage> phase_a_rule_coverage()
{
	return {
	    {"LR-001", ConstructHandling::kSupported, "implicit data member read", false},
	    {"LR-002", ConstructHandling::kSupported, "explicit this data member read", false},
	    {"LR-003", ConstructHandling::kSupported, "data member mutation", false},
	    {"LR-004", ConstructHandling::kSupported, "return statement", false},
	    {"LR-005", ConstructHandling::kSupported, "if statement", false},
	    {"LR-006", ConstructHandling::kSupported, "built-in expression", false},
	    {"LR-007", ConstructHandling::kSupported, "same-class nonvirtual helper candidate", false},
	    {"LR-008", ConstructHandling::kBoundary, "static member calls are boundary candidates",
	        false},
	    {"LR-009", ConstructHandling::kBoundary, "free function calls are boundary candidates",
	        false},
	    {"LR-010", ConstructHandling::kModeled, "global state is modeled as env", false},
	    {"LR-011", ConstructHandling::kModeled, "base state is modeled explicitly", false},
	    {"LR-012", ConstructHandling::kModeled, "virtual calls require dispatch table", false},
	    {"LR-013", ConstructHandling::kBoundary, "overloaded operators are resolved boundaries",
	        false},
	    {"LR-014", ConstructHandling::kSupported, "local variable declaration", false},
	    {"LR-015", ConstructHandling::kConservative, "loops are conservative paths in Phase A",
	        false},
	    {"LR-016", ConstructHandling::kConservative, "range-for is conservative in Phase A", false},
	    {"LR-017", ConstructHandling::kSupported, "lambda without this capture", false},
	    {"LR-018", ConstructHandling::kModeled, "lambda with this capture maps to self", false},
	    {"LR-019", ConstructHandling::kSupported, "noexcept is reported from method metadata",
	        false},
	    {"LR-020", ConstructHandling::kModeled, "raw this escape requires object_ref", false},
	    {"LR-021", ConstructHandling::kModeled, "return this requires object_ref", false},
	    {"LR-022", ConstructHandling::kModeled, "return *this requires object_ref/self view",
	        false},
	    {"LR-023", ConstructHandling::kModeled, "dynamic_cast requires type_tag", false},
	    {"LR-024", ConstructHandling::kModeled, "typeid requires type_tag", false},
	    {"LR-025", ConstructHandling::kBoundary, "reinterpret_cast this requires byte boundary",
	        false},
	    {"LR-026", ConstructHandling::kModeled, "delete this requires lifetime state", false},
	    {"LR-027", ConstructHandling::kModeled, "explicit destructor call requires lifetime state",
	        false},
	    {"LR-028", ConstructHandling::kModeled, "placement new on this requires lifetime state",
	        false},
	    {"LR-029", ConstructHandling::kModeled, "field address requires addressable cell", false},
	    {"LR-030", ConstructHandling::kNotYetImplemented,
	        "member function pointer is reported only", false},
	    {"LR-031", ConstructHandling::kNotYetImplemented, "constructor target is outside Phase A",
	        false},
	    {"LR-032", ConstructHandling::kNotYetImplemented, "destructor target is outside Phase A",
	        false},
	    {"LR-033", ConstructHandling::kSupported,
	        "instantiated function template specializations are inspectable", false},
	    {"LR-034", ConstructHandling::kConservative, "macro source mapping is conservative", false},
	    {"LR-035", ConstructHandling::kSupported,
	        "throw expression is preserved as exception intent", false},
	    {"LR-036", ConstructHandling::kConservative, "try/catch is conservative in Phase A", false},
	    {"LR-037", ConstructHandling::kSupported,
	        "structured binding field expansion when bindings resolve to record fields", false},
	    {"LR-038", ConstructHandling::kNotYetImplemented, "coroutines are future work", false},
	    {"LR-039", ConstructHandling::kSupported,
	        "unevaluated contexts are tracked without effects", false},
	    {"LR-040", ConstructHandling::kNotYetImplemented,
	        "default member initializer is future work", false},
	    {"LR-041", ConstructHandling::kSupported, "conditional operator is expression control flow",
	        false},
	    {"LR-042", ConstructHandling::kSupported, "default arguments are supplied by Clang Sema",
	        false},
	    {"LR-043", ConstructHandling::kSupported, "auto type is recorded after semantic resolution",
	        false},
	    {"LR-044", ConstructHandling::kSupported,
	        "casts and std::move/std::forward are resolved expressions", false},
	    {"LR-045", ConstructHandling::kBoundary,
	        "const_cast requires mutability-aware boundary handling", false},
	    {"LR-046", ConstructHandling::kSupported, "break/continue statements are tracked", false},
	    {"LR-047", ConstructHandling::kSupported,
	        "cv/ref member qualifiers are part of target metadata", false},
	    {"LR-048", ConstructHandling::kModeled,
	        "access control is reported without rewriting product visibility", false},
	    {"LR-049", ConstructHandling::kConservative,
	        "constructor calls in method bodies require construction-aware lowering", false},
	};
}

} // namespace azteca::plan
